name: works-of-agnes-martin

source-dirs:
  - src
dependencies:
  - base
  - diagrams-lib
  - diagrams-svg

executables:
  HappyHoliday:
    main: HappyHoliday.hs

  Untitled1977:
    main: Untitled1977.hs

  Untitled5:
    main: Untitled5.hs
